---

- collections:
  - dellemc.os10
  connection: network_cli
  gather_facts: false
  hosts:
    - switches

  vars:
    jenkinsgit: https://github.com/plukkie/Jenkins_CICD_Pipeline_OS10_Fabric.git
    jenkinsdir: ./jenkinsgit
    settingsfile: settings.json
    host_vars_dir: host_vars
    group_vars_dir: group_vars
    inventoryfile: hosts


  tasks: 
  
    - name: Fetch Git {{ jenkinsgit }}
      delegate_to: localhost
      run_once: true
      git:
        repo: "{{ jenkinsgit }}"
        dest: "{{ jenkinsdir }}"

    - name: Register {{ settingsfile }} in JSON format
      delegate_to: localhost
      run_once: true
      shell: cat {{ jenkinsdir }}"/"{{ settingsfile }}
      register: settingsobj

    - name: Store {{ settingsfile }} into variable
      delegate_to: localhost
      run_once: true
      set_fact:
        jsonobj: "{{ settingsobj.stdout | from_json }}"

    - name: Construct group yaml file '{{ group_vars_dir }}/all.yaml'
      delegate_to: localhost
      run_once: true
      template:
        src: templates/create_fabric_all_base.j2
        dest: "{{ group_vars_dir }}/all.yaml"

    - name: Construct host yaml files in '{{ host_vars_dir }}/*'
      delegate_to: localhost
      template:
        src: templates/create_fabric_hostvar_files.j2
        dest: "{{ host_vars_dir }}/{{ inventory_hostname }}.yaml"



