---
- hosts: leafs
  connection: network_cli
  gather_facts: false
  collections:
    - dellemc.os10

  vars:
    refevi: 999
    leafcount: "{{ groups['leafs'] | length }}"
    spinecount: "{{ groups['spines'] | length }}"

  tasks: 

   - name: Request EVI {{ checkvni }} status...
     vars:
       ansible_connection: network_cli
     any_errors_fatal: true
     os10_command:
       commands:
         - show evpn evi {{ refevi }}
         - show evpn mac evi {{ refevi }} count

     register: evi_log


   - name: Closed Loop Verification - EVI status

     debug:
       msg: "Checked EVI status"
     when: evi_log is search ("EVI.*up")
     failed_when: evi_log is not search ("EVI.*up")

   - name: Closed Loop Verification - EVI mac count

     vars:
       maccount: evi_log is search ("Remote MAC Address Count :").split(":")[1]

     debug:
       msg: "Checked EVI mac count"
     when: evi_log is search ("Remote MAC Address Count :").split(":")[1]
     failed_when: evi_log is not search ("EVI.*up")



   - name: Print log results evi check
     debug:
       var: evi_log

