



hostname: os10-SPINE-2

os10_bgp:
  asn: 65001
  best_path:
    as_path: multipath-relax
  graceful_restart: true
  maxpath_ebgp: 2
  neighbor:
  - adv_interval: 1
    fall_over: present
    name: spine-leaf
    timer: 3 9
    type: peergroup
  - address_family:
    - type: ipv4
    admin: up
    adv_interval: 1
    fall_over: present
    ip: 192.168.1.8
    name: spine 1 Underlay
    peergroup: spine-leaf
    timer: 3 9
    type: ipv4
    remote_asn: 64625
    sender_loop_detect: false
  - address_family:
    - activate: false
      type: ipv4
    - activate: true
      type: l2vpn
    admin: up
    adv_interval: 1
    fall_over: present
    ip: 10.0.2.1
    name: spine 1 Overlay
    peergroup: spine-leaf
    remote_asn: 64625
    send_community:
    - state: present
      type: extended
    sender_loop_detect: false
    src_loopback: 0
    timer: 3 9
    type: ipv4
  - address_family:
    - type: ipv4
    admin: up
    adv_interval: 1
    fall_over: present
    ip: 192.168.1.10
    name: spine 2 Underlay
    peergroup: spine-leaf
    timer: 3 9
    type: ipv4
    remote_asn: 64625
    sender_loop_detect: false
  - address_family:
    - activate: false
      type: ipv4
    - activate: true
      type: l2vpn
    admin: up
    adv_interval: 1
    fall_over: present
    ip: 10.0.2.2
    name: spine 2 Overlay
    peergroup: spine-leaf
    remote_asn: 64625
    send_community:
    - state: present
      type: extended
    sender_loop_detect: false
    src_loopback: 0
    timer: 3 9
    type: ipv4
  - address_family:
    - type: ipv4
    admin: up
    adv_interval: 1
    fall_over: present
    ip: 192.168.1.12
    name: spine 3 Underlay
    peergroup: spine-leaf
    timer: 3 9
    type: ipv4
    remote_asn: 64626
    sender_loop_detect: false
  - address_family:
    - activate: false
      type: ipv4
    - activate: true
      type: l2vpn
    admin: up
    adv_interval: 1
    fall_over: present
    ip: 10.0.2.3
    name: spine 3 Overlay
    peergroup: spine-leaf
    remote_asn: 64626
    send_community:
    - state: present
      type: extended
    sender_loop_detect: false
    src_loopback: 0
    timer: 3 9
    type: ipv4
  - address_family:
    - type: ipv4
    admin: up
    adv_interval: 1
    fall_over: present
    ip: 192.168.1.14
    name: spine 4 Underlay
    peergroup: spine-leaf
    timer: 3 9
    type: ipv4
    remote_asn: 64626
    sender_loop_detect: false
  - address_family:
    - activate: false
      type: ipv4
    - activate: true
      type: l2vpn
    admin: up
    adv_interval: 1
    fall_over: present
    ip: 10.0.2.4
    name: spine 4 Overlay
    peergroup: spine-leaf
    remote_asn: 64626
    send_community:
    - state: present
      type: extended
    sender_loop_detect: false
    src_loopback: 0
    timer: 3 9
    type: ipv4
  - admin: up
    ip: 192.168.168.0
    type: ipv4
    remote_asn: 65001
  redistribute:
  - address_type: ipv4
    route_map_name: spine-leaf
    route_type: connected
  router-id: 10.0.1.2

os10_interface:
  ethernet 1/1/1: 
    admin: up
    switchport: false
    desc: interlink to leaf 1
    mtu: 9216
    ip_and_mask: 192.168.1.8/31
  ethernet 1/1/2: 
    admin: up
    switchport: false
    desc: interlink to leaf 2
    mtu: 9216
    ip_and_mask: 192.168.1.10/31
  ethernet 1/1/3: 
    admin: up
    switchport: false
    desc: interlink to leaf 3
    mtu: 9216
    ip_and_mask: 192.168.1.12/31
  ethernet 1/1/4: 
    admin: up
    switchport: false
    desc: interlink to leaf 4
    mtu: 9216
    ip_and_mask: 192.168.1.14/31
  loopback 0:
    admin: up
    ip_and_mask: 10.0.1.2/32

os10_lldp:
  enable: true

os10_ntp:
  server:
  - ip: 10.204.11.135
    prefer: true

os10_prefix_list:
- entries:
  - condition_list:
    - condition: ge
      prelen: '24'
    mask: '8'
    net_num: 10.0.0.0
    number: 10
    permit: true
    state: present
  - condition_list:
    - condition: ge
      prelen: '24'
    mask: '16'
    net_num: 192.168.0.0
    number: 20
    permit: true
    state: present
  name: spine-leaf
  state: present
  type: ipv4

os10_route_map:
  route_map:
  - match:
    - ip_type: ipv4
      prefix_list: spine-leaf
    name: spine-leaf
    permit: true
    seq_num: 10

os10_system:
  hostname: os10-SPINE-2 


os10_xstp:
  intf: {}
