



hostname: os10-LEAF-4

os10_bgp:
  asn: 64626
  best_path:
    as_path: multipath-relax
  graceful_restart: true
  maxpath_ebgp: 2
  neighbor:
  - adv_interval: 1
    fall_over: present
    name: spine-leaf
    timer: 3 9
    type: peergroup
  - address_family:
    - type: ipv4
      allow_as_in: 1
    admin: up
    adv_interval: 1
    fall_over: present
    ip: 192.168.1.25
    name: spine 1 Underlay
    peergroup: spine-leaf
    timer: 3 9
    type: ipv4
    remote_asn: 65001
  - address_family:
    - activate: false
      type: ipv4
    - activate: true
      type: l2vpn
    admin: up
    adv_interval: 1
    ebgp_multihop: 4
    fall_over: present
    ip: 10.0.1.1
    name: spine 1 Overlay
    peergroup: spine-leaf
    remote_asn: 65001
    send_community:
    - state: present
      type: extended
    sender_loop_detect: false
    src_loopback: 0
    timer: 3 9
    type: ipv4
  - address_family:
    - type: ipv4
      allow_as_in: 1
    admin: up
    adv_interval: 1
    fall_over: present
    ip: 192.168.1.27
    name: spine 2 Underlay
    peergroup: spine-leaf
    timer: 3 9
    type: ipv4
    remote_asn: 65001
  - address_family:
    - activate: false
      type: ipv4
    - activate: true
      type: l2vpn
    admin: up
    adv_interval: 1
    ebgp_multihop: 4
    fall_over: present
    ip: 10.0.1.2
    name: spine 2 Overlay
    peergroup: spine-leaf
    remote_asn: 65001
    send_community:
    - state: present
      type: extended
    sender_loop_detect: false
    src_loopback: 0
    timer: 3 9
    type: ipv4
  - address_family:
    - type: ipv4
      allow_as_in: 1
    admin: up
    adv_interval: 1
    fall_over: present
    ip: 192.168.1.29
    name: spine 3 Underlay
    peergroup: spine-leaf
    timer: 3 9
    type: ipv4
    remote_asn: 65002
  - address_family:
    - activate: false
      type: ipv4
    - activate: true
      type: l2vpn
    admin: up
    adv_interval: 1
    ebgp_multihop: 4
    fall_over: present
    ip: 10.0.1.3
    name: spine 3 Overlay
    peergroup: spine-leaf
    remote_asn: 65002
    send_community:
    - state: present
      type: extended
    sender_loop_detect: false
    src_loopback: 0
    timer: 3 9
    type: ipv4
  - address_family:
    - type: ipv4
      allow_as_in: 1
    admin: up
    adv_interval: 1
    fall_over: present
    ip: 192.168.1.31
    name: spine 4 Underlay
    peergroup: spine-leaf
    timer: 3 9
    type: ipv4
    remote_asn: 65002
  - address_family:
    - activate: false
      type: ipv4
    - activate: true
      type: l2vpn
    admin: up
    adv_interval: 1
    ebgp_multihop: 4
    fall_over: present
    ip: 10.0.1.4
    name: spine 4 Overlay
    peergroup: spine-leaf
    remote_asn: 65002
    send_community:
    - state: present
      type: extended
    sender_loop_detect: false
    src_loopback: 0
    timer: 3 9
    type: ipv4
  - admin: up
    ip: 192.168.168.2
    type: ipv4
    remote_asn: 64626
  redistribute:
  - address_type: ipv4
    route_map_name: spine-leaf
    route_type: connected
  router-id: 10.0.2.4

os10_interface:
  ethernet 1/1/4: 
    admin: up
    switchport: false
    desc: interlink to spine 1
    mtu: 9216
    ip_and_mask: 192.168.1.24/31
  ethernet 1/1/8: 
    admin: up
    switchport: false
    desc: interlink to spine 2
    mtu: 9216
    ip_and_mask: 192.168.1.26/31
  ethernet 1/1/12: 
    admin: up
    switchport: false
    desc: interlink to spine 3
    mtu: 9216
    ip_and_mask: 192.168.1.28/31
  ethernet 1/1/16: 
    admin: up
    switchport: false
    desc: interlink to spine 4
    mtu: 9216
    ip_and_mask: 192.168.1.30/31
  ethernet 1/1/9:
    admin: up
    switchport: false
    desc: VLT-interlink to leaf 3
  ethernet 1/1/10:
    admin: up
    switchport: false
    desc: VLT-interlink to leaf 3
  ethernet 1/1/11:
    admin: up
    switchport: false
    desc: VLT-interlink to leaf 3
  ethernet 1/1/12:
    admin: up
    switchport: false
    desc: VLT-interlink to leaf 3
  virtual-network 999999:
    vrf: Vrf1
    ip_and_mask: 172.16.0.4/24
    virtual_gateway_ip: "172.16.0.254"
    admin: up
    desc: "Fabric wide vxlan 999999"
  loopback 0:
    admin: up
    ip_and_mask: 10.0.2.4/32
  loopback 1:
    admin: up
    ip_and_mask: 10.10.10.3
  ethernet 1/1/3:
    admin: up
    desc: to host 1
    mtu: 9216
    portmode: trunk
    switchport: true
  ethernet 1/1/7:
    admin: up
    desc: to host 2
    mtu: 9216
    portmode: trunk
    switchport: true

os10_lldp:
  enable: true

os10_ntp:
  server:
  - ip: 10.204.11.135
    prefer: true

os10_prefix_list:
- entries:
  - condition_list:
    - condition: ge
      prelen: 32
    mask: '0'
    net_num: 0.0.0.0
    number: 10
    permit: true
    state: present
  - condition_list:
    - condition: ge
      prelen: 31
    mask: '0'
    net_num: 0.0.0.0
    number: 20
    permit: true
    state: present
  name: deny_v4_host_routes
  state: present
  type: ipv4
- entries:
  - condition_list:
    - condition: ge
      prelen: '24'
    mask: '8'
    net_num: 10.0.0.0
    number: 30
    permit: true
    state: present
  - condition_list:
    - condition: ge
      prelen: '24'
    mask: '16'
    net_num: 192.168.0.0
    number: 50
    permit: true
    state: present
  name: spine-leaf
  state: present
  type: ipv4

os10_route_map:
  route_map:
  - match:
    - ip_type: ipv4
      prefix_list: spine-leaf
    name: spine-leaf
    permit: true
    seq_num: 10
  - match:
    - ip_type: ipv4
      prefix_list: deny_v4_host_routes
    name: deny_v4_host_routes
    permit: true
    seq_num: 10

os10_system:
  hostname: os10-LEAF-4 

os10_vlan:
  Vlan 999:
    description: "Cluster management"
    ip_and_mask: null
    state: present
    untagged_members:
    - port: ethernet 1/1/3
      state: present
    - port: ethernet 1/1/7
      state: present
  Vlan 4000:
    description: iBGP_link
    ip_and_mask: 192.168.168.3/31
    state: present

os10_vlt:
  discovery_intf: 1/1/9-1/1/13
  discovery_intf_state: present
  domain: 34
  peer_routing: true
  vlt_mac: 00:00:00:00:00:03

os10_xstp:
  enable: true
  intf:
    ethernet 1/1/3:
      edge_port: true
    ethernet 1/1/7:
      edge_port: true
  rstp:
    bridge_priority: 0
  type: rstp

os10_vrf:
  vrfdetails:
    - vrfname: "Vrf1"
      state: present

