



hostname: os10-LEAF-3

os10_bgp:
  asn: 64626
  best_path:
    as_path: multipath-relax
  graceful_restart: true
  maxpath_ebgp: 2
  neighbor:
  - adv_interval: 1
    fall_over: present
    name: spine-leaf
    timer: 3 9
    type: peergroup
  - address_family:
    - allow_as_in: 1
      type: ipv4
    admin: up
    adv_interval: 1
    fall_over: present
    ip: 192.168.1.17
    name: spine 1 Underlay
    peergroup: spine-leaf
    timer: 3 9
    type: ipv4
    remote_asn: 65001
  - address_family:
    - activate: false
      type: ipv4
    - activate: true
      type: l2vpn
    admin: up
    adv_interval: 1
    ebgp_multihop: 4
    fall_over: present
    ip: 10.0.1.1
    name: spine 1 Overlay
    peergroup: spine-leaf
    remote_asn: 65001
    send_community:
    - state: present
      type: extended
    sender_loop_detect: false
    src_loopback: 0
    timer: 3 9
    type: ipv4
  - address_family:
    - allow_as_in: 1
      type: ipv4
    admin: up
    adv_interval: 1
    fall_over: present
    ip: 192.168.1.19
    name: spine 2 Underlay
    peergroup: spine-leaf
    timer: 3 9
    type: ipv4
    remote_asn: 65001
  - address_family:
    - activate: false
      type: ipv4
    - activate: true
      type: l2vpn
    admin: up
    adv_interval: 1
    ebgp_multihop: 4
    fall_over: present
    ip: 10.0.1.2
    name: spine 2 Overlay
    peergroup: spine-leaf
    remote_asn: 65001
    send_community:
    - state: present
      type: extended
    sender_loop_detect: false
    src_loopback: 0
    timer: 3 9
    type: ipv4
  - address_family:
    - allow_as_in: 1
      type: ipv4
    admin: up
    adv_interval: 1
    fall_over: present
    ip: 192.168.1.21
    name: spine 3 Underlay
    peergroup: spine-leaf
    timer: 3 9
    type: ipv4
    remote_asn: 65002
  - address_family:
    - activate: false
      type: ipv4
    - activate: true
      type: l2vpn
    admin: up
    adv_interval: 1
    ebgp_multihop: 4
    fall_over: present
    ip: 10.0.1.3
    name: spine 3 Overlay
    peergroup: spine-leaf
    remote_asn: 65002
    send_community:
    - state: present
      type: extended
    sender_loop_detect: false
    src_loopback: 0
    timer: 3 9
    type: ipv4
  - address_family:
    - allow_as_in: 1
      type: ipv4
    admin: up
    adv_interval: 1
    fall_over: present
    ip: 192.168.1.23
    name: spine 4 Underlay
    peergroup: spine-leaf
    timer: 3 9
    type: ipv4
    remote_asn: 65002
  - address_family:
    - activate: false
      type: ipv4
    - activate: true
      type: l2vpn
    admin: up
    adv_interval: 1
    ebgp_multihop: 4
    fall_over: present
    ip: 10.0.1.4
    name: spine 4 Overlay
    peergroup: spine-leaf
    remote_asn: 65002
    send_community:
    - state: present
      type: extended
    sender_loop_detect: false
    src_loopback: 0
    timer: 3 9
    type: ipv4
  - admin: up
    ip: 192.168.168.3
    type: ipv4
    remote_asn: 64626
  redistribute:
  - address_type: ipv4
    route_map_name: spine-leaf
    route_type: connected
  router-id: 10.0.2.3

os10_interface:
  ethernet 1/1/4: 
    admin: up
    switchport: false
    desc: interlink to spine 1
    mtu: 9216
    ip_and_mask: 192.168.1.16/31
  ethernet 1/1/8: 
    admin: up
    switchport: false
    desc: interlink to spine 2
    mtu: 9216
    ip_and_mask: 192.168.1.18/31
  ethernet 1/1/12: 
    admin: up
    switchport: false
    desc: interlink to spine 3
    mtu: 9216
    ip_and_mask: 192.168.1.20/31
  ethernet 1/1/16: 
    admin: up
    switchport: false
    desc: interlink to spine 4
    mtu: 9216
    ip_and_mask: 192.168.1.22/31


